---
title: "Replication of Study 3 by Stavrova, Ehlebracht & Vohs (2020, Journal of Experimental Psychology)"
author: "Eric Neumann (ericnm@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---


##Introduction


### Background and Replication Choice

Cynicism is highly prevalent in the US these days, and most of its correlates are negative. One relevant question is thus why it manages to sustain itself in the light of its many disadvantages. Stavrova et al (2020) propose an interesting self-reinforcing circle of cynicism: being cynical makes you treat others with more disrespect, and as they will treat you with more disrespect in turn, you are more likely to be cynical. Study 3 of their paper examines this latter part, finding that recalling an experience of being disrespected leads people to be more cynical about human nature. As much of my PhD research will likely build on this finding, I would like to first see if the results are robust and replicable.

### Stimuli and Procedures

Participants were recruited on Prolific.com. They were first asked to write a short essay about a time they had experienced disrespect (experimental condition) or guilt (control condition). This was followed by a manipulation check where participants indicated the extent to which they felt disrespected or guilty. All subjects then completed the cynical distrust scale (Greenglass & Julkunen, 1989). As participants might have seen through the experimental design, they also filled out the Perceived Awareness of the Research Hypothesis scale (PARH; Rubin, 2010). Finally, they completed an attention check and basic demographic questions. 

### Anticipated Challenges

I anticipate my primary challenge to be the coding of the analysis of the PARH scale as the original paper proposed four different ways perceived awareness can be measured. I do think, however, that learning this will be useful for future studies and also estimate the rest of the analysis to be straightforward enough to allow for time exploring the impact of participant's perceived awareness of the intentions behind the study.

### Pertinent Links

This replication attempt is documented in Github [here.](https://github.com/psych251/stavrova2020)
The original paper, within the same repository, can be found [here.](https://github.com/psych251/stavrova2020/blob/master/original_paper/paper.pdf)


##Methods


###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
